### ISSUE TITLE
The Code of Pyspark with folium

### ISSUE THREAD

**Issue by HADDADENICAR** [yuzzfeng/spatialSpark#1]
I've a research for my final year project .
pyspark didn't worked with folium for me.
could you give the code of pyspark with folium please 
thanks

**Comment by yuzzfeng** [comment]
pyspark and folium should normally not have any conflicts. The problems may caused by installation of the packages.

**Comment by HADDADENICAR** [comment]
Actually folium objects can be pickled(serialized) for me, for that i asked your code to know how you do that.
i have posted an issue [here](https://github.com/python-visualization/folium/issues/878) about this ,and the answer was negative.
so how you pickled the folium objects ?

**Comment by yuzzfeng** [comment]
The current repo is only using folium to visualize the results and did not combine this in the pyspark commands.

Of course, you may try to first save your temporary results and visualize afterwards. I personally also regard this could not be achieved inside the pyspark functions.
